const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const ProcessingEngine = require('./processingEngine');

/**
 * Feature Module: Caption Studio Rendering Engine
 * Responsibilities: SRT, VTT, ASS subtitle generation and FFmpeg burned-in video export
 */
class RenderingEngine {
  static formatSrtTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const date = new Date(null);
    date.setMilliseconds(s * 1000);
    const timeStr = date.toISOString().substring(11, 23);
    return timeStr.replace('.', ',');
  }

  static formatVttTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const date = new Date(null);
    date.setMilliseconds(s * 1000);
    return date.toISOString().substring(11, 23);
  }

  static generateSrtString(subtitles = [], styleConfig = {}) {
    if (!subtitles || subtitles.length === 0) {
      const defaultText = styleConfig.uppercase ? "WELCOME TO AI CREATOR DASHBOARD!" : "Welcome to AI Creator Dashboard!";
      return `1\n00:00:00,000 --> 00:00:04,500\n${defaultText}`;
    }

    return subtitles
      .map((sub, idx) => {
        const start = this.formatSrtTimestamp(sub.start || idx * 3);
        const end = this.formatSrtTimestamp(sub.end || (idx + 1) * 3);
        let text = sub.text || sub.content || '';
        if (styleConfig.uppercase) text = text.toUpperCase();
        return `${idx + 1}\n${start} --> ${end}\n${text}`;
      })
      .join('\n\n');
  }

  static generateVttString(subtitles = []) {
    const header = `WEBVTT - Generated by AI Creator Dashboard Caption Studio\n\n`;
    if (!subtitles || subtitles.length === 0) {
      return header + `00:00:00.000 --> 00:00:04.500\nWelcome to AI Creator Dashboard!`;
    }

    const body = subtitles
      .map((sub, idx) => {
        const start = this.formatVttTimestamp(sub.start || idx * 3);
        const end = this.formatVttTimestamp(sub.end || (idx + 1) * 3);
        return `${start} --> ${end}\n${sub.text || sub.content || ''}`;
      })
      .join('\n\n');

    return header + body;
  }

  static generateAssString(subtitles = [], styleConfig = {}) {
    const fontName = styleConfig.fontFamily || 'Arial';
    const fontSize = styleConfig.fontSize || 28;
    const primaryColor = styleConfig.primaryColor ? this.hexToAssColor(styleConfig.primaryColor) : '&H00FFFFFF';
    const isTransparent = styleConfig.transparentBg === true || 
      styleConfig.backgroundOpacity === 0 || 
      styleConfig.backgroundColor === 'transparent' || 
      !styleConfig.backgroundColor;
    const backColor = !isTransparent && styleConfig.backgroundColor 
      ? this.hexToAssColor(styleConfig.backgroundColor, styleConfig.backgroundOpacity ?? 0.75) 
      : '&HFF000000';
    const strokeColor = styleConfig.strokeColor ? this.hexToAssColor(styleConfig.strokeColor) : '&H00000000';

    const header = `[Script Info]
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontName},${fontSize},${primaryColor},&H00000000,${strokeColor},${backColor},1,0,0,0,100,100,0,0,1,${styleConfig.strokeWidth || 2},${styleConfig.shadowOffset || 2},2,10,10,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

    const events = subtitles.map((sub) => {
      const start = this.formatAssTimestamp(sub.start || 0);
      const end = this.formatAssTimestamp(sub.end || 0);
      const text = (sub.text || '').replace(/\n/g, '\\N');
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
    }).join('\n');

    return header + events;
  }

  static formatAssTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = Math.floor(s % 60);
    const cs = Math.floor((s % 1) * 100);

    const hh = h.toString();
    const mm = m.toString().padStart(2, '0');
    const ss = sec.toString().padStart(2, '0');
    const cscs = cs.toString().padStart(2, '0');

    return `${hh}:${mm}:${ss}.${cscs}`;
  }

  static hexToAssColor(hex, opacity = 1.0) {
    if (!hex || typeof hex !== 'string') return '&H00FFFFFF';
    const cleanHex = hex.replace('#', '');
    let r = 'FF', g = 'FF', b = 'FF';
    if (cleanHex.length === 6) {
      r = cleanHex.substring(0, 2);
      g = cleanHex.substring(2, 4);
      b = cleanHex.substring(4, 6);
    }
    const alphaNum = Math.round((1 - opacity) * 255).toString(16).padStart(2, '0').toUpperCase();
    return `&H${alphaNum}${b.toUpperCase()}${g.toUpperCase()}${r.toUpperCase()}`;
  }

  static getVideoInfo(ffmpegBin, videoPath) {
    return new Promise((resolve) => {
      exec(`"${ffmpegBin}" -i "${videoPath}"`, (err, stdout, stderr) => {
        const text = (stderr || '') + (stdout || '') + (err?.message || '');
        const match = text.match(/Video:.* (\d{3,4})x(\d{3,4})/);
        if (match) {
          resolve({ width: parseInt(match[1], 10), height: parseInt(match[2], 10) });
        } else {
          resolve({ width: 720, height: 1280 }); // Standard vertical default
        }
      });
    });
  }

  static hexToRgba(hex, opacity = 1.0) {
    if (!hex) return 'transparent';
    const cleanHex = hex.replace('#', '');
    if (cleanHex.length !== 6) return hex;
    const r = parseInt(cleanHex.substring(0, 2), 16);
    const g = parseInt(cleanHex.substring(2, 4), 16);
    const b = parseInt(cleanHex.substring(4, 6), 16);
    return `rgba(${r}, ${g}, ${b}, ${opacity})`;
  }

  /**
   * Burn subtitles onto video using Headless Chromium with 100% pixel-perfect 1:1 match to Preview Canvas
   */
  static renderBurnedVideo(videoPath, subtitles, styleConfig = {}) {
    return new Promise(async (resolve) => {
      let ffmpegBin = 'ffmpeg';
      try { ffmpegBin = require('ffmpeg-static') || 'ffmpeg'; } catch (e) {}

      let puppeteer;
      try {
        puppeteer = require('puppeteer');
      } catch (e) {
        console.warn('[Rendering Engine] Puppeteer is not installed. Fallback to unedited video.');
        return resolve({ videoUrl: videoPath, isFallback: true });
      }

      // Determine video resolution and target output resolution
      const { width: srcW, height: srcH } = await this.getVideoInfo(ffmpegBin, videoPath);

      // If video is low-resolution (< 720p), upscale canvas to minimum 720p for crisp creator export
      let targetW = srcW;
      let targetH = srcH;
      if (targetW < 720) {
        targetW = 720;
        targetH = Math.round((srcH / srcW) * 720);
        if (targetH % 2 !== 0) targetH++;
      }
      if (targetW % 2 !== 0) targetW++;

      // Preview canvas base dimension: 340px for vertical (9:16), 640px for landscape (16:9), 400px for square
      const basePreviewW = targetH >= targetW ? 340 : (Math.abs(targetW - targetH) < 50 ? 400 : 640);
      const scale = targetW / basePreviewW;

      const tempDir = path.dirname(videoPath) || process.cwd();
      const runId = Date.now();
      const outputFilename = `rendered_${runId}.mp4`;
      const outputVideoPath = path.join(tempDir, outputFilename);
      const framesDir = path.join(tempDir, `frames_${runId}`);
      fs.mkdirSync(framesDir, { recursive: true });

      try {
        const isTransparent = styleConfig.transparentBg === true || 
          styleConfig.backgroundOpacity === 0 || 
          styleConfig.backgroundColor === 'transparent' || 
          !styleConfig.backgroundColor;
          
        const bgOpacity = styleConfig.backgroundOpacity !== undefined ? styleConfig.backgroundOpacity : 0.8;
        const bgColor = isTransparent ? 'transparent' : this.hexToRgba(styleConfig.backgroundColor || '#000000', bgOpacity);

        const fontSizePx = Math.round((styleConfig.fontSize || 28) * scale);
        const paddingVPx = Math.round((isTransparent ? 4 : 6) * scale);
        const paddingHPx = Math.round((isTransparent ? 10 : 16) * scale);
        const borderRadiusPx = Math.round((isTransparent ? 6 : 10) * scale);
        
        // Exact overlay positioning matching VideoPreview.jsx
        let containerPositionCss = `
          left: 0;
          right: 0;
          bottom: ${Math.round(64 * scale)}px;
          justify-content: center;
        `;

        if (styleConfig.position === 'top') {
          containerPositionCss = `
            left: 0;
            right: 0;
            top: ${Math.round(48 * scale)}px;
            justify-content: center;
          `;
        } else if (styleConfig.position === 'center') {
          containerPositionCss = `
            left: 0;
            right: 0;
            top: 50%;
            transform: translateY(-50%);
            justify-content: center;
          `;
        } else if (styleConfig.position === 'custom') {
          containerPositionCss = `
            top: ${styleConfig.posY ?? 75}%;
            left: ${styleConfig.posX ?? 50}%;
            transform: translate(-50%, -50%);
            width: 100%;
            justify-content: center;
          `;
        }

        const borderCSS = (!isTransparent && bgOpacity > 0.3) 
          ? `${Math.max(1, Math.round(1 * scale))}px solid rgba(255,255,255,0.1)` 
          : 'none';

        const boxShadowCSS = (!isTransparent && bgOpacity > 0.4) 
          ? `0 ${Math.round(4 * scale)}px ${Math.round(18 * scale)}px rgba(0,0,0,0.35)` 
          : 'none';

        const shadowOffset = styleConfig.shadowOffset || 0;
        const shadowColor = styleConfig.shadowColor || 'rgba(0,0,0,0.85)';
        const textShadowCSS = shadowOffset > 0
          ? `${Math.round(shadowOffset * scale)}px ${Math.round(shadowOffset * scale)}px ${Math.round(shadowOffset * 1.5 * scale)}px ${shadowColor}`
          : 'none';
          
        const strokeCSS = (styleConfig.strokeWidth && styleConfig.strokeWidth > 0)
          ? `${Math.round(styleConfig.strokeWidth * scale)}px ${styleConfig.strokeColor || '#000000'}`
          : 'none';

        const fontName = styleConfig.fontFamily || 'Montserrat';
        const textTransform = styleConfig.uppercase ? 'uppercase' : 'none';
        const letterSpacingCSS = (styleConfig.letterSpacing ? Math.round(styleConfig.letterSpacing * scale) : 0) + 'px';

        const htmlTemplate = `
        <!DOCTYPE html>
        <html>
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Anton&family=Bangers&family=Bebas+Neue&family=Inter:wght@400;600;700;800;900&family=Montserrat:wght@400;600;700;800;900&family=Oswald:wght@500;700&family=Outfit:wght@400;600;700;800;900&family=Poppins:wght@600;700;800&family=Righteous&family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">
          <style>
            * { box-sizing: border-box; }
            body {
              margin: 0;
              padding: 0;
              width: ${targetW}px;
              height: ${targetH}px;
              background-color: transparent;
              overflow: hidden;
              position: relative;
            }
            .overlay-container {
              position: absolute;
              ${containerPositionCss}
              padding: 0 ${Math.round(16 * scale)}px;
              display: flex;
              box-sizing: border-box;
            }
            .caption-box {
              font-family: '${fontName}', system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
              font-size: ${fontSizePx}px;
              font-weight: ${styleConfig.fontWeight || '700'};
              color: ${styleConfig.primaryColor || '#FFFFFF'};
              background-color: ${bgColor};
              padding: ${paddingVPx}px ${paddingHPx}px;
              border-radius: ${borderRadiusPx}px;
              border: ${borderCSS};
              box-shadow: ${boxShadowCSS};
              text-shadow: ${textShadowCSS};
              -webkit-text-stroke: ${strokeCSS};
              letter-spacing: ${letterSpacingCSS};
              text-transform: ${textTransform};
              display: flex;
              flex-wrap: wrap;
              justify-content: center;
              gap: 0.22em;
              max-width: 92%;
              line-height: 1.25;
              text-align: center;
              word-break: break-word;
              box-sizing: border-box;
            }
          </style>
        </head>
        <body>
          <div class="overlay-container">
            <div id="caption" class="caption-box"></div>
          </div>
        </body>
        </html>
        `;

        const htmlPath = path.join(framesDir, 'template.html');
        fs.writeFileSync(htmlPath, htmlTemplate);

        const browser = await puppeteer.launch({
          headless: 'new',
          args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        const page = await browser.newPage();
        await page.setViewport({ width: targetW, height: targetH, deviceScaleFactor: 1 });
        await page.goto(`file://${htmlPath}`);
        // Ensure web fonts are completely loaded before taking frames
        await page.evaluateHandle('document.fonts.ready');

        const animation = styleConfig.animation || 'none';
        const highlightColor = styleConfig.highlightColor || '#FFD700';

        const concatLines = ['ffconcat version 1.0'];
        let lastEnd = 0;

        for (let i = 0; i < subtitles.length; i++) {
          const sub = subtitles[i];
          const start = parseFloat(sub.start) || 0;
          const end = parseFloat(sub.end) || 0;
          const duration = Math.max(0.1, end - start);
          
          if (start > lastEnd) {
            // Gap between subtitles
            concatLines.push(`file 'empty.png'`);
            concatLines.push(`duration ${(start - lastEnd).toFixed(3)}`);
          }

          const text = (sub.text || sub.content || '').trim();
          const words = text.split(/\s+/).filter(Boolean);

          if (animation === 'none' || words.length === 0) {
            await page.evaluate((txt) => {
              const el = document.getElementById('caption');
              el.style.display = 'flex';
              el.innerText = txt;
            }, text);

            const pngName = `frame_${i}.png`;
            const pngPath = path.join(framesDir, pngName);
            await page.screenshot({ path: pngPath, omitBackground: true });

            concatLines.push(`file '${pngName}'`);
            concatLines.push(`duration ${duration.toFixed(3)}`);
          } else {
            const timePerWord = duration / words.length;
            
            for (let w = 0; w < words.length; w++) {
              await page.evaluate(({ wordsArray, currentIdx, animType, hColor }) => {
                const container = document.getElementById('caption');
                container.style.display = 'flex';
                container.innerHTML = '';
                
                wordsArray.forEach((word, idx) => {
                  const span = document.createElement('span');
                  span.innerText = word;
                  
                  const isCurrent = idx === currentIdx;
                  const isPast = idx < currentIdx;
                  let visible = true;
                  
                  switch (animType) {
                    case 'highlight':
                      if (isCurrent) span.style.color = hColor;
                      break;
                    case 'karaoke':
                      if (isCurrent || isPast) span.style.color = hColor;
                      break;
                    case 'typewriter':
                      if (idx > currentIdx) visible = false;
                      break;
                    case 'scale-up':
                      if (isCurrent) {
                        span.style.transform = 'scale(1.25)';
                        span.style.color = hColor;
                      }
                      break;
                    case 'bounce':
                      if (isCurrent) {
                        span.style.transform = 'translateY(-10px) scale(1.15)';
                        span.style.color = hColor;
                      }
                      break;
                  }
                  
                  if (visible) {
                    span.style.display = 'inline-block';
                    container.appendChild(span);
                  }
                });
              }, { wordsArray: words, currentIdx: w, animType: animation, hColor: highlightColor });

              const pngName = `frame_${i}_w_${w}.png`;
              const pngPath = path.join(framesDir, pngName);
              await page.screenshot({ path: pngPath, omitBackground: true });

              concatLines.push(`file '${pngName}'`);
              concatLines.push(`duration ${timePerWord.toFixed(3)}`);
            }
          }
          
          lastEnd = end;
        }

        // Generate full-resolution empty transparent PNG for gaps
        await page.evaluate(() => {
          const el = document.getElementById('caption');
          el.innerText = '';
          el.style.display = 'none';
        });
        const emptyPngPath = path.join(framesDir, 'empty.png');
        await page.screenshot({ path: emptyPngPath, omitBackground: true });

        // Add empty frame at the very end
        concatLines.push(`file 'empty.png'`);
        
        await browser.close();

        const concatPath = path.join(framesDir, 'concat.txt');
        fs.writeFileSync(concatPath, concatLines.join('\n'));

        const escapedConcatFile = concatPath.replace(/\\/g, '/');
        const filterStr = (srcW < targetW)
          ? `[0:v]scale=${targetW}:${targetH}:flags=lanczos[bg];[1:v]fps=30[sub];[bg][sub]overlay=0:0`
          : `[1:v]fps=30[sub];[0:v][sub]overlay=0:0`;

        const command = `"${ffmpegBin}" -i "${path.basename(videoPath)}" -f concat -safe 0 -i "${escapedConcatFile}" -filter_complex "${filterStr}" -c:v libx264 -preset ultrafast -crf 22 -c:a aac -b:a 192k "${outputFilename}" -y`;

        exec(command, { cwd: tempDir, timeout: 180000 }, (error, stdout, stderr) => {
          // Cleanup frames directory
          try { fs.rmSync(framesDir, { recursive: true, force: true }); } catch (e) {}

          if (error || !fs.existsSync(outputVideoPath)) {
            console.warn(`[Rendering Engine Notice] FFmpeg video rendering error: ${error ? error.message : 'Output file missing'}\nStderr: ${stderr}`);
            return resolve({ videoUrl: videoPath, isFallback: true });
          }

          resolve({ videoUrl: outputVideoPath, isFallback: false });
        });
      } catch (err) {
        console.warn(`[Rendering Engine Error] ${err.message}`);
        try { fs.rmSync(framesDir, { recursive: true, force: true }); } catch (e) {}
        resolve({ videoUrl: videoPath, isFallback: true });
      }
    });
  }
}

module.exports = RenderingEngine;
