const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const ProcessingEngine = require('./processingEngine');

/**
 * Feature Module: Caption Studio Rendering Engine
 * Responsibilities: SRT, VTT, ASS subtitle generation and FFmpeg burned-in video export
 */
class RenderingEngine {
  static formatSrtTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const date = new Date(null);
    date.setMilliseconds(s * 1000);
    const timeStr = date.toISOString().substring(11, 23);
    return timeStr.replace('.', ',');
  }

  static formatVttTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const date = new Date(null);
    date.setMilliseconds(s * 1000);
    return date.toISOString().substring(11, 23);
  }

  static generateSrtString(subtitles = []) {
    if (!subtitles || subtitles.length === 0) {
      return `1\n00:00:00,000 --> 00:00:04,500\nWelcome to AI Creator Dashboard!`;
    }

    return subtitles
      .map((sub, idx) => {
        const start = this.formatSrtTimestamp(sub.start || idx * 3);
        const end = this.formatSrtTimestamp(sub.end || (idx + 1) * 3);
        return `${idx + 1}\n${start} --> ${end}\n${sub.text || sub.content || ''}`;
      })
      .join('\n\n');
  }

  static generateVttString(subtitles = []) {
    const header = `WEBVTT - Generated by AI Creator Dashboard Caption Studio\n\n`;
    if (!subtitles || subtitles.length === 0) {
      return header + `00:00:00.000 --> 00:00:04.500\nWelcome to AI Creator Dashboard!`;
    }

    const body = subtitles
      .map((sub, idx) => {
        const start = this.formatVttTimestamp(sub.start || idx * 3);
        const end = this.formatVttTimestamp(sub.end || (idx + 1) * 3);
        return `${start} --> ${end}\n${sub.text || sub.content || ''}`;
      })
      .join('\n\n');

    return header + body;
  }

  static generateAssString(subtitles = [], styleConfig = {}) {
    const fontName = styleConfig.fontFamily || 'Arial';
    const fontSize = styleConfig.fontSize || 28;
    const primaryColor = styleConfig.primaryColor ? this.hexToAssColor(styleConfig.primaryColor) : '&H00FFFFFF';
    const backColor = styleConfig.backgroundColor ? this.hexToAssColor(styleConfig.backgroundColor, styleConfig.backgroundOpacity || 0.75) : '&H80000000';
    const strokeColor = styleConfig.strokeColor ? this.hexToAssColor(styleConfig.strokeColor) : '&H00000000';

    const header = `[Script Info]
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontName},${fontSize},${primaryColor},&H00000000,${strokeColor},${backColor},1,0,0,0,100,100,0,0,1,${styleConfig.strokeWidth || 2},${styleConfig.shadowOffset || 2},2,10,10,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

    const events = subtitles.map((sub) => {
      const start = this.formatAssTimestamp(sub.start || 0);
      const end = this.formatAssTimestamp(sub.end || 0);
      const text = (sub.text || '').replace(/\n/g, '\\N');
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
    }).join('\n');

    return header + events;
  }

  static formatAssTimestamp(seconds) {
    const s = Math.max(0, parseFloat(seconds) || 0);
    const date = new Date(null);
    date.setMilliseconds(s * 1000);
    const timeStr = date.toISOString().substring(11, 22);
    return timeStr.startsWith('0') ? timeStr.substring(1) : timeStr;
  }

  static hexToAssColor(hex, opacity = 1.0) {
    if (!hex || typeof hex !== 'string') return '&H00FFFFFF';
    const cleanHex = hex.replace('#', '');
    let r = 'FF', g = 'FF', b = 'FF';
    if (cleanHex.length === 6) {
      r = cleanHex.substring(0, 2);
      g = cleanHex.substring(2, 4);
      b = cleanHex.substring(4, 6);
    }
    const alphaNum = Math.round((1 - opacity) * 255).toString(16).padStart(2, '0').toUpperCase();
    return `&H${alphaNum}${b.toUpperCase()}${g.toUpperCase()}${r.toUpperCase()}`;
  }

  /**
   * Burn subtitles onto video using FFmpeg with CWD execution to prevent Windows space escaping bugs.
   */
  static renderBurnedVideo(videoPath, subtitles, styleConfig = {}) {
    return new Promise((resolve) => {
      const tempDir = path.dirname(videoPath) || process.cwd();
      const assFilename = `sub_${Date.now()}.ass`;
      const assPath = path.join(tempDir, assFilename);
      const outputFilename = `rendered_${Date.now()}.mp4`;
      const outputVideoPath = path.join(tempDir, outputFilename);

      try {
        const assContent = this.generateAssString(subtitles, styleConfig);
        fs.writeFileSync(assPath, assContent);

        // FFmpeg command using CWD relative paths to bypass Windows path space escaping issues
        const command = `ffmpeg -i "${path.basename(videoPath)}" -vf "subtitles='${assFilename}'" -c:a copy "${outputFilename}" -y`;

        exec(command, { cwd: tempDir, timeout: 60000 }, (error) => {
          try { fs.unlinkSync(assPath); } catch (e) {}

          if (error || !fs.existsSync(outputVideoPath)) {
            console.warn(`[Rendering Engine Notice] FFmpeg video rendering fallback: ${error ? error.message : 'Output file missing'}`);
            return resolve({ videoUrl: videoPath, isFallback: true });
          }

          resolve({ videoUrl: outputVideoPath, isFallback: false });
        });
      } catch (err) {
        console.warn(`[Rendering Engine Error] ${err.message}`);
        resolve({ videoUrl: videoPath, isFallback: true });
      }
    });
  }
}

module.exports = RenderingEngine;
